services:
  jobfinder:
    build: .
    container_name: jobfinder-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
      - JWT_ACCESS=${JWT_ACCESS}
      - JWT_REFRESH=${JWT_REFRESH}
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  database: